### ISSUE TITLE
issue with form action path 

### ISSUE THREAD

**Issue by beshad** [bcairns/silverstripe-backuprestore#1]
hi, great yet simple module. but there seems to be an issue with the from action path when either backup or restore buttons are clicked. mine defaults to localhost/admin/backuprestore/backup every time i click backup button which obviously breaks the site (should be localhost/MY_PROJECT_NAME/admin/backuprestore/backup). problem goes away and module does what is supposed to do when i change the path from /admin/backuprestore/backup to admin/backuprestore/backup (without the / at the beginning of url) in BackupRestore_Content.ss file. is this a bug or something is wrong with my code? i can do a pull request if needed. thanks

**Comment by bcairns** [comment]
Thanks for reporting, I hadn't tested this in a site running in a sub-folder. I've added the fix.
