### ISSUE TITLE
Hardcoded resource URL breaks when resources-dir is modified

### ISSUE THREAD

**Issue by davejtoews** [bcairns/silverstripe-backuprestore#3]
Its possible to redefine the resources directory in composer.json like so: 

    "extra": {
        "resources-dir": "_resources"
    }

The hardcoded icon URL in BackupRestore.php will cause an error if the path has changed:

    private static $menu_icon = 'public/resources/vendor/bcairns/silverstripe-backuprestore/images/menuicon.png';

There is also a hardcoded path in the template.

For my purposes, I managed to fix with a hacky fork, but this is less than ideal:

https://github.com/davejtoews/silverstripe-backuprestore/commit/fbad9f6344295847d542126ff4710cdbcbb0cc18

**Comment by bcairns** [comment]
Fixed in 4.0.1
